#!/bin/sh
# postinst script for vx-dga-l-google-chrome-extensions
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
		
		DIREXTENSIONS="/opt/google/chrome/extensions"
		if ! test -d "$DIREXTENSIONS" ;  then
			mkdir -p "$DIREXTENSIONS"
			chmod +rx "$DIREXTENSIONS"
    	fi
    	
    	# Declaramos las extensiones disponibles en el paquete
    	DIRBASE="/usr/share/vitalinux/google-chrome-extensions"
    	SCREENCASTIFY="mmeijimgabbpbgpdklnllpncmdofkcpn.json"
    	OFFICEONLINE="ndjpnladcallmjemlbaebfadecfhkepb.json"
    	COPIARPEGAROFFICEONLINE="ifbmcpbgkhlpfcodhjhdbllhiaomkdej.json"
    	ADDBLOCKPLUS="cfhdojbkjhnklbpkdaibdccddilifddb.json"
    	VIDEODOWNLOADHELPER="lmjnegcaeklhafolokijcfjliaokphfk.json"
    	S2BOT4SCRATCH="pllkalmkifgmanfoghenhgafbcpbicdj.json"
    	ZERONOISECLASSRROOM="pgpkohbgbjmihckldcacljomfkkaogjd.json"
		UBLOCK="cjpalhdlnbpafiamejdnhcphjbkeiagm.json"
		BITBLOQ="ddpdpmibfdhifigignfdiggfbcmfblfj.json"

		# Las asignamos por etiqueta. Si tuviera más se aplicarían todas
		if [ -f /tmp/migasfree.tags ]; then
 			ETIQUETAS=$(cat /tmp/migasfree.tags)
		else
  			ETIQUETAS="$(migasfree-tags -g)"
		fi
		if (echo "$ETIQUETAS" | grep SEC-LUISBUNUEL.AULAINF > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${S2BOT4SCRATCH} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp "${DIRBASE}/${EXTENSION}" ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep SEC-VALDERROBRES > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${UBLOCK} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp "${DIRBASE}/${EXTENSION}" ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep SEC-MIGUELSERVET > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${SCREENCASTIFY} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp "${DIRBASE}/${EXTENSION}" ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep MIGUELSERVET.PCSAULA > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${ZERONOISECLASSRROOM} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp "${DIRBASE}/${EXTENSION}" ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep PER-AULARAGON > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${SCREENCASTIFY} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp "${DIRBASE}/${EXTENSION}" ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep SEC-CORONADEARAGON > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${OFFICEONLINE} ${COPIARPEGAROFFICEONLINE} ${ADDBLOCKPLUS} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp ${DIRBASE}/${EXTENSION} ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep SEC-SANALBERTO > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${VIDEODOWNLOADHELPER} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp ${DIRBASE}/${EXTENSION} ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep CEN-CAREI > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${VIDEODOWNLOADHELPER} ${OFFICEONLINE} ${COPIARPEGAROFFICEONLINE} \
				${ADDBLOCKPLUS} ${SCREENCASTIFY} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp ${DIRBASE}/${EXTENSION} ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep CPA-RIBAGORZA > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${VIDEODOWNLOADHELPER} ${ADDBLOCKPLUS} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp ${DIRBASE}/${EXTENSION} ${DIREXTENSIONS}
				fi
			done
		fi

		if (echo "$ETIQUETAS" | grep SEC-CONDEARANDA > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${BITBLOQ} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp ${DIRBASE}/${EXTENSION} ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep SEC-MIGUELDEMOLINOS > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${BITBLOQ} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp ${DIRBASE}/${EXTENSION} ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep -E 'SEC-GOYA.AULAS|GOYA.AULASINF|GOYA.SALASPROF' > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${BITBLOQ} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp ${DIRBASE}/${EXTENSION} ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep SEC-LUCASMALLADA > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${VIDEODOWNLOADHELPER} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp ${DIRBASE}/${EXTENSION} ${DIREXTENSIONS}
				fi
			done
		fi
		if (echo "$ETIQUETAS" | grep AYTO.BIESCAS > /dev/null 2> /dev/null) ; then
			for EXTENSION in ${S2BOT4SCRATCH} ; do
				if ! test -f ${DIREXTENSIONS}/${EXTENSION} ; then
					cp ${DIRBASE}/${EXTENSION} ${DIREXTENSIONS}
				fi
			done
		fi

		# Las extensiones deben tener permiso de lectura para todos
		chmod -R +r ${DIREXTENSIONS}
		;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
